name: Bug Report
description: You found a bug.
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: backend
    attributes:
      label: Backend impacted
      description: Which backend is concerned with your bug report?
      options:
        - The PyTorch implementation
        - The MLX implementation
        - The Rust implementation
        - Other / All
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      description: What is your operating system?
      options:
        - Linux
        - Mac OS X
        - Windows (unsupported)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      description: What hardware are you using?
      options:
        - CPU
        - GPU with CUDA
        - Metal with MLX
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of your bug.
      placeholder: 
      value: 
    validations:
      required: true
  - type: textarea
    id: more_info
    attributes:
      label: Extra information
      description: Please provide any other relevant information, such as log extracts, code etc.
      placeholder: 
      value: 
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: 
      description: Please provide any other relevant information, such as log extracts, code etc.
      placeholder: 
      value: |
          Fill in the following information on your system.
          - Operating system version:

          If the backend impacted is PyTorch:
          - Python version:
          - PyTorch version:
          - CUDA version (run `python -c 'import torch;  print(torch.version.cuda)'`):
          - GPU model and memory:
            
          If the backend is MLX:
          - Mac model:
    validations:
      required: true
