[workspace]
members = [
    "mimi-pyo3",
    "moshi-backend",
    "moshi-cli",
    "moshi-core",
]
resolver = "2"

[workspace.dependencies]
candle = { version = "0.6.0", package = "candle-core" }
candle-nn = "0.6.0"
candle-transformers = "0.6.0"
candle-flash-attn = "0.6.0"
