[project]
name = "moshi"
version = "0.0.1"
requires-python = ">= 3.10"
description = "Moshi is moshi"
dependencies = [
    "numpy >= 2.1.0, < 2.2",
    "safetensors >= 0.4.0, < 0.5",
    "huggingface-hub >= 0.24, < 0.25",
    "einops == 0.7",
    "sentencepiece == 0.2",
    "sounddevice == 0.5",
    "sphn >= 0.1.4",
    "torch >= 2.2.0, < 2.5",
    "websockets >= 11.0.3, < 11.1",
]
authors = [{name="Laurent Mazaré", email="laurent@kyutai.org"}]
maintainers = [{name="Laurent Mazaré", email="laurent@kyutai.org"}]


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["moshi", "moshi.utils", "moshi.modules", "moshi.models", "moshi.quantization"]
