on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, refacto ]

name: Continuous integration

jobs:
  check:
    name: Check
    defaults:
      run:
        working-directory: ./rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/rust_build
      - name: check
        shell: bash
        run: |
          cargo check
