on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    defaults:
      run:
        working-directory: ./rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: check
        shell: bash
        run: |
          cargo check
